#- shell:
    # TODO: delete! probably dont need it
    #- npm config set prefix '~/.npm-global'
    # TODO: Automate filling in the list
    # TODO: Install go tools
    # - go get -u github.com/m3ng9i/ran
    # TODO: Install rust tools
    # TODO: Install npm global tools
    # - npm install -g @fabiospampinato/bump
    # TODO: install vs code extensions
    # - code --list-extensions

# Symlink files
- link:
    # Zsh
    ~/.zshrc: zsh/zshrc.zsh
    ~/.zprofile: zsh/zprofile.zsh
    # Git
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    # Sublime Text
    "~/Library/Application Support/Sublime Text 3/Packages/User": sublime
    # Neovim
    ~/.config/nvim: nvim
    # VS Code
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
    ~/Library/Application Support/Code/User/keybindings.json: vscode/keybindings.json
