# Settings
- defaults:
    link:
      create: true
      relink: true
      force: true # Swap the original file

# TODO: ?
- clean: ['~', '~/.config']

# Run shell commands
- shell:
    # Install submodules
    - [git submodule update --init --recursive, Installing submodules]

# Symlink files
- link:
    # Zsh
    ~/.zshrc: zsh/zshrc.zsh
    # Git
    ~/.gitconfig: git/gitconfig
    ~/.gitignore_global: git/gitignore_global
    # Hammerspoon
    ~/.hammerspoon: hammerspoon
    # Sublime Text
    "~/Library/Application Support/Sublime Text 3/Packages/User": sublime
    # Neovim
    ~/.config/nvim: nvim
    # VS Code
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
    ~/Library/Application Support/Code/User/keybindings.json: vscode/keybindings.json
